---
title: "Create table of stressors"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output:
  word_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
  html_document:
    code_folding: hide
    highlight: haddock
    includes:
      in_header: ~/github/src/templates/ohara_hdr.html
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}
source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')

source(here::here('common_fxns.R'))
library(flextable)
```


# Summary

This script creates table S1, aligning IUCN threats with CHI stressors

# Methods

Gather processed sensitivity dataframe.

```{r}

spp_incl <- get_incl_spp()

```

## Match threat codes to stressors

```{r}
threat_to_stressor <- read_csv(here('_raw/iucn_threat_to_stressor_lookup.csv')) %>%
  mutate(code_main = str_extract(code, '[0-9]+') %>% as.numeric(),
         code_short = str_extract(code, '[0-9]+\\.[0-9]+')) %>%
  mutate(stressor = str_split(stressor, ';')) %>%
  unnest(stressor) %>%
  separate(desc, into = c('desc_main', 'desc_sub', 'desc_subsub'), 
           sep = ': ', remove = FALSE)

thr_to_spp <- spp_incl %>%
  left_join(threat_to_stressor, by = c('code', 'stressor', 'category')) %>%
  mutate(desc_main = sprintf('%s. %s', code_main, desc_main),
         desc_sub = sprintf('%s. %s', code_short, desc_sub)) %>%
  select(code_main, desc_main, desc_sub, stressor, iucn_sid, category) %>%
  filter(!is.na(stressor)) %>%
  distinct()

repeated_strs <- c('Nutrient pollution', 'Direct human')

threat_table <- thr_to_spp %>%
  left_join(read_csv(here('_raw/stressor_names.csv')), by = 'stressor') %>%
  group_by(code_main, desc_main, desc_sub, str_desc)  %>%
  summarize(n_spp = n_distinct(iucn_sid)) %>%
  ungroup() %>%
  arrange(code_main, str_desc) %>%
  select(-code_main) %>%
  mutate(str_desc = ifelse(str_desc %in% repeated_strs, paste0(str_desc, '*'), str_desc)) %>%
  setNames(c('Threat category', 'Threat subcategory', 'Stressor', 'n spp'))

write_csv(threat_table, here('ms_tables/s1_table_threat_spp.csv'))

flextable(threat_table) %>%
  theme_vanilla() %>%
  align(part = 'all', align = 'left') %>%
  align(part = 'all', j = 4, align = 'center') %>%
  # bg(bg = 'white', part = 'header') %>%
  # border(border.bottom = officer::fp_border(), part = 'header') %>%
  font(font = 'Arial', part = 'all') %>%
  fontsize(size = 8, part = 'all') %>%
  width(1:2, width = 2.5) %>%
  width(3, width = 1) %>%
  merge_v(j = 1:3)
  
```

