---
title: 'Generate a list of taxonomic ranks'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/src/templates/ohara_hdr.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')

source(here('common_fxns.R'))

```


# Summary

For plotting by taxonomic group, generate a table of taxonomic group labels and counts.  Because this focuses on the included species (i.e. `get_incl_spp()` function), it must come *after* the species stressor sensitivities have been determined.

# Methods

```{r}
spp_incl <- get_incl_spp()

rank_df <- read_csv(file.path(dir_bd_anx, 
                              sprintf('iucn/spp_info_from_api_%s.csv', api_version))) %>%
  janitor::clean_names() %>%
  filter(iucn_sid %in% spp_incl$iucn_sid) %>%
  select(iucn_sid, kingdom:family) %>%
  mutate_if(is.character, .fun = function(x) tools::toTitleCase(tolower(x)))

spp_ranks <- spp_incl %>%
  left_join(rank_df, by = 'iucn_sid') %>%
  mutate(rank = case_when(phylum == 'Chordata' ~ class, 
                          kingdom == 'Plantae' ~ kingdom,
                          TRUE ~ phylum))

write_csv(spp_ranks %>% 
            select(iucn_sid, kingdom:rank) %>% 
            distinct(), 
          here('int/spp_ranks.csv'))
```

``` {r}

spp_rank_by_str <- spp_ranks %>%
  filter(!is.na(stressor)) %>%
  group_by(stressor, rank) %>%
  summarize(n_spp = n_distinct(iucn_sid))
spp_rank_by_str_cat <- spp_ranks %>%
  filter(!is.na(stressor)) %>%
  group_by(category, rank) %>%
  summarize(n_spp = n_distinct(iucn_sid),
            stressor = paste0('cum_', first(category)))
spp_rank_all_impact <- spp_ranks %>%
  group_by(rank) %>%
  filter(!is.na(stressor)) %>%
  summarize(n_spp = n_distinct(iucn_sid),
            stressor = 'cum_all')

spp_rank_combo <- bind_rows(spp_rank_by_str, 
                            spp_rank_by_str_cat, 
                            spp_rank_all_impact) %>%
  select(rank, stressor, n_spp)
all_rank_combo <- spp_rank_combo %>%
  group_by(stressor) %>%
  summarize(n_spp = sum(n_spp),
            rank = 'All spp')

all_thr <- spp_ranks %>%
  group_by(rank) %>%
  summarize(n_spp_thr = n_distinct(iucn_sid)) %>%
  bind_rows(spp_ranks %>%
              summarize(n_spp_thr = n_distinct(iucn_sid),
                        rank = 'all spp'))

df <- bind_rows(spp_rank_combo, all_rank_combo) %>%
  left_join(all_thr, by = 'rank')
  
DT::datatable(df)

write_csv(df, here('int/spp_count_by_taxon_stressor.csv'))
```
