---
title: 'How it works: maps showing the process step by step'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/src/templates/ohara_hdr.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      echo = TRUE, message = FALSE, warning = FALSE)

library(raster)
library(sf)
library(cowplot)
source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')

library(showtext)
font_add(family = 'bentonbold', 
         regular = file.path('/Library/Fonts', 
                             'BentonSans Condensed Bold', 
                             'BentonSans Condensed Bold.otf'))
font_add(family = 'benton', 
         regular = file.path('/Library/Fonts', 
                             'BentonSans Condensed Book', 
                             'BentonSans Condensed Book.otf'))
showtext_auto()

reload <- TRUE
```


# Summary

Generate maps (as static image) for Shiny app - 

* species range
* distribution of relevant stressors
* intersection showing impacted, non-impacted

``` {r spp_dist_maps}
spp_ids <- c(8005, 19488, 39374, 2475, 7750, 21860, 133384, 2694870)

ocean_rast <- raster(here('_spatial/ocean_area_mol.tif'))
cell_id_rast <- raster(here('_spatial/cell_id_mol.tif'))
for(id in spp_ids) {
  # read in map
  range <- read_csv()
  # plot it
  # use cowplot to arrange on page
  # save it
}

fig2a_impact_ct_map <- ggplot() +
  ggtheme_map(base_size = 7) +
  geom_raster(data = imp_ct_df, aes(x, y, fill = xfm_imp_ct)) +
  geom_sf(data = land_sf, fill = 'grey96', color = 'grey40', size = .10) +
  scale_fill_viridis_c(breaks = ct_breaks,
                       labels = ct_labels,
                       na.value = 'grey80') +
  theme(text = element_text(family = 'benton'),
        plot.margin = unit(c(.05, 0, .05, 0), units = 'cm'),
        legend.background = element_blank(),
        legend.key.width = unit(.25, 'cm'),
        legend.title = element_blank()) +
  coord_sf(datum = NA) + ### ditch graticules
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))

```