---
title: 'Reproject stressors'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/src/templates/ohara_hdr.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

library(raster)
source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')

source(here::here('common_fxns.R'))

dir_str_mol <- '/home/shares/ohi/git-annex/impact_acceleration/stressors'
### this is an absolute path to git-annex on Mazu
dir_bd_anx <- '~/git-annex/bd_chi' ### this is on git-annex in home/ohara
dir_str_gp  <- here('layers/stressors_gp') ### relative path in github

```

# Summary

Test different projections to identify the error in mapping GP to Mollweide

# Data Sources

Halpern et al. 2019.

# Methods

## Create cell ID lookup for spp CRS to chi CRS

Use the old ocean raster to identify the projection and resolution; reproject the cell_id raster to match, using nearest neighbor.

```{r}

cell_id_mol_file <- file.path(dir_bd_anx, 'spatial/cell_id_mol.tif')
ocean_mol_file <- file.path(dir_bd_anx, 'spatial/ocean_mol.tif')
if(!file.exists(ocean_mol_file)) {
  file.copy(from = '/home/shares/ohi/model/GL-NCEAS-Halpern2008/tmp/ocean.tif',
            to = ocean_mol_file)
}

if(!file.exists(cell_id_mol_file)) {
  
  ocean_area_mol <- raster(ocean_mol_file)

  cell_id_gp <- raster('_spatial/cell_id_rast.tif')
  cell_id_mol <- cell_id_gp %>% 
    projectRaster(ocean_area_mol, method = 'ngb', over = TRUE)
  
  # cell_id_mol_mask <- cell_id_mol %>%
  #   mask(ocean_area_mol)
  
  writeRaster(cell_id_mol, cell_id_mol_file, overwrite = TRUE)
}
```

``` {r}
cell_id_mol <- raster(cell_id_mol_file)
plot(cell_id_mol, 'cell id gp to mol')

cell_id_gp <- raster('_spatial/cell_id_rast.tif')
plot(cell_id_gp, main = 'cell id gp native')
ocean_area_mol <- raster(ocean_mol_file)
plot(ocean_area_mol, main = 'ocean area, moll native')
ocean_area_gp <- raster('_spatial/ocean_area_rast.tif')
plot(ocean_area_gp, main = 'ocean area, gp native')

ocean_area_mol2gp <- ocean_area_mol %>%
    projectRaster(cell_id_gp, method = 'ngb', over = TRUE)
plot(ocean_area_mol2gp, main = 'ocean area mol to gp')

ocean_area_gp2mol <- ocean_area_gp %>%
    projectRaster(ocean_area_mol, method = 'ngb', over = TRUE)
plot(ocean_area_gp2mol, main = 'ocean area gp to mol')

test_ext <- extent(c(xmin = -180, xmax = 180, 
                     ymin = -90, ymax = 90))
test_rast <- raster(x = test_ext, res = 0.1,
                    crs = crs('+init=epsg:4326'))
values(test_rast) <- 1:ncell(test_rast)
plot(test_rast, main = 'cell id, wgs84 0.1 deg native (11 km at eq)')

test_rast_gp <- projectRaster(test_rast, ocean_area_gp, method = 'ngb')
plot(test_rast_gp, main = 'cell id, wgs84 to gp')

test_rast_mol <- projectRaster(test_rast, ocean_area_mol, method = 'ngb')
plot(test_rast_mol, main = 'cell id, wgs84 to mollweide')

test_rast_gp_mol <- projectRaster(test_rast_gp, ocean_area_mol, method = 'ngb')
plot(test_rast_gp_mol, main = 'cell id, wgs84 to gp to mollweide')

ocean_area_gp2wgs84 <- projectRaster(ocean_area_gp, test_rast, method = 'ngb')
plot(ocean_area_gp2wgs84, main = 'ocean area, gp to wgs84')

ocean_area_gp2wgs842mol <- projectRaster(ocean_area_gp2wgs84, ocean_area_mol, method = 'ngb')
plot(ocean_area_gp2wgs842mol, main = 'ocean area, gp to wgs84 to mollweide')
```
